networks:
  loki:

volumes:
  prometheus:

services:
  web_app:
    image: dirakon/devops-py:latest
    mem_limit: 100m
    ports:
      - "8089:80"
    networks:
      - loki
    volumes:
      - ./app_py_data/:/app/data/
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"

  web_app_cs:
    image: dirakon/devops-cs:latest
    mem_limit: 100m
    ports:
      - "8087:7273"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"

  loki:
    image: grafana/loki:2.9.2
    mem_limit: 100m
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /var/log:/var/log
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"

  promtail:
    mem_limit: 100m
    ports:
      - "9080:9080"
    image: grafana/promtail:2.9.2
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/log:/var/log
      - ./promtail_config:/etc/promtail
      - ./.positions:/var/lib/promtail/positions
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"

  grafana:
    mem_limit: 100m
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
  prometheus:
    mem_limit: 100m
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - loki
    volumes:
      - ./prometheus_config/:/etc/prometheus/
      - prometheus:/prometheus
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"