global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "self"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]
  - job_name: "web_app_cs"
    static_configs:
      - targets: ["web_app_cs:7273"]
  - job_name: "web_app"
    static_configs:
      - targets: ["web_app:80"]