name: Python app - testing

on:
  push:
    paths:
      - 'app_python/**'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11.7", "3.11.8", "3.12" ]
    defaults:
      run:
        working-directory: app_python

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --output-format=github .

      - name: Test with Pytest
        run: |
          pytest