name: Python app - security

on: [ push ]

jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app_python

    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.7'

      - name: Snyk monitor
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}