name: C# app - security

on: [ push ]

jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app_csharp

    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.1'
      - name: Download the dependencies with cache
        run: dotnet restore --locked-mode

      - name: Snyk monitor
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}