name: Python app - security

on: [ push ]

jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app_python

    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.7'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Snyk monitor
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}